# Scikit-learn

In [ ]:
from sklearn import datasets
dir(datasets)

['__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_arff_parser',
 '_base',
 '_california_housing',
 '_covtype',
 '_kddcup99',
 '_lfw',
 '_olivetti_faces',
 '_openml',
 '_rcv1',
 '_samples_generator',
 '_species_distributions',
 '_svmlight_format_fast',
 '_svmlight_format_io',
 '_twenty_newsgroups',
 'clear_data_home',
 'dump_svmlight_file',
 'fetch_20newsgroups',
 'fetch_20newsgroups_vectorized',
 'fetch_california_housing',
 'fetch_covtype',
 'fetch_kddcup99',
 'fetch_lfw_pairs',
 'fetch_lfw_people',
 'fetch_olivetti_faces',
 'fetch_openml',
 'fetch_rcv1',
 'fetch_species_distributions',
 'get_data_home',
 'load_breast_cancer',
 'load_diabetes',
 'load_digits',
 'load_files',
 'load_iris',
 'load_linnerud',
 'load_sample_image',
 'load_sample_images',
 'load_svmlight_file',
 'load_svmlight_files',
 'load_wine',
 'make_biclusters',
 'make_blobs',
 'make_checkerboard',
 'make_circl

These datasets contain two types of variables:

*   Feature Variables-Variables which are used for input.These are fed into the ML Model in order for the mdel to make the predictions.
*   Target Variables-These are output variables which are the expected output.These act as reference of the how the prediction should be understandable and presentable.tha datase is converted into pandas.



 feature variables = inputs
                 target variables are = output

In [ ]:
data1=datasets.load_breast_cancer()

In [ ]:
data1

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

The input data in stored in the x variable,whereas ontl the target data(which in the case in output reference)

In [ ]:
import numpy as np
import pandas as pd
data2=pd.DataFrame(data1.data,columns=data1.feature_names)
data2

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst radius  worst texture  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     worst perimeter  worst area  worst smoothness  worst compactness  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     worst concavity  worst concave points  worst symmetry  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

In [ ]:
x = data2
y = data1.target



In [ ]:
x

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst radius  worst texture  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     worst perimeter  worst area  worst smoothness  worst compactness  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     worst concavity  worst concave points  worst symmetry  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [ ]:
x.describe()

mean radius  mean texture  mean perimeter    mean area  \
count   569.000000    569.000000      569.000000   569.000000   
mean     14.127292     19.289649       91.969033   654.889104   
std       3.524049      4.301036       24.298981   351.914129   
min       6.981000      9.710000       43.790000   143.500000   
25%      11.700000     16.170000       75.170000   420.300000   
50%      13.370000     18.840000       86.240000   551.100000   
75%      15.780000     21.800000      104.100000   782.700000   
max      28.110000     39.280000      188.500000  2501.000000   

       mean smoothness  mean compactness  mean concavity  mean concave points  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       mean symmetry  mean fractal dimension  ...  worst radius  \
count     569.000000              569.000000  ...    569.000000   
mean        0.181162                0.062798  ...     16.269190   
std         0.027414                0.007060  ...      4.833242   
min         0.106000                0.049960  ...      7.930000   
25%         0.161900                0.057700  ...     13.010000   
50%         0.179200                0.061540  ...     14.970000   
75%         0.195700                0.066120  ...     18.790000   
max         0.304000                0.097440  ...     36.040000   

       worst texture  worst perimeter   worst area  worst smoothness  \
count     569.000000       569.000000   569.000000        569.000000   
mean       25.677223       107.261213   880.583128          0.132369   
std         6.146258        33.602542   569.356993          0.022832   
min        12.020000        50.410000   185.200000          0.071170   
25%        21.080000        84.110000   515.300000          0.116600   
50%        25.410000        97.660000   686.500000          0.131300   
75%        29.720000       125.400000  1084.000000          0.146000   
max        49.540000       251.200000  4254.000000          0.222600   

       worst compactness  worst concavity  worst concave points  \
count         569.000000       569.000000            569.000000   
mean            0.254265         0.272188              0.114606   
std             0.157336         0.208624              0.065732   
min             0.027290         0.000000              0.000000   
25%             0.147200         0.114500              0.064930   
50%             0.211900         0.226700              0.099930   
75%             0.339100         0.382900              0.161400   
max             1.058000         1.252000              0.291000   

       worst symmetry  worst fractal dimension  
count      569.000000               569.000000  
mean         0.290076                 0.083946  
std          0.061867                 0.018061  
min          0.156500                 0.055040  
25%          0.250400                 0.071460  
50%          0.282200                 0.080040  
75%          0.317900                 0.092080  
max          0.663800                 0.207500  

[8 rows x 30 columns]

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
Model = LinearRegression() #First Step:Provide the algorithm - Basic Model


The data is fitted inside the model and as algorithm is installed for the model to make the predictions from the data.Now let's see if the model can make predictions closer to the assigned target variables.

In [ ]:
Model.fit(x,y)

LinearRegression()

In [ ]:
Model.predict(x)

array([-4.55748245e-02,  1.57869645e-01, -1.31319863e-01, -1.92288185e-01,
        1.65553403e-01,  3.01137442e-01,  1.50292603e-01,  3.68008882e-01,
        3.01789947e-01, -1.54652777e-01,  4.52284915e-01,  1.41528218e-01,
        3.58799952e-01,  5.42350255e-01,  3.74158760e-01,  6.59600231e-03,
        2.00106593e-01, -1.59903421e-02, -6.86648217e-02,  6.72592533e-01,
        1.02825052e+00,  1.12677621e+00,  2.64794750e-01,  1.48388507e-02,
       -1.56499389e-01, -1.81494969e-01,  7.15639403e-02,  1.05751382e-01,
        4.69024100e-03,  4.64984176e-01, -6.42440721e-02,  8.49150658e-02,
       -1.09544105e-01,  4.72282004e-03,  8.30995041e-02,  1.06438245e-01,
        4.10004938e-01,  1.00702985e+00,  7.26754362e-01,  4.37172612e-01,
        6.74438947e-01,  5.68674205e-01, -2.03827234e-01,  3.31302150e-01,
        3.41861785e-01, -7.01785970e-02,  1.29121705e+00,  1.86405824e-01,
        8.88890773e-01,  6.88486808e-01,  9.57028129e-01,  9.28752105e-01,
        9.27637316e-01,  

KNeighborsRegressor Algorithm

In [ ]:
from sklearn.neighbors import KNeighborsRegressor

In [ ]:
Mod1 = KNeighborsRegressor()

In [ ]:
Mod1.fit(x,y)

KNeighborsRegressor()

In [ ]:
Mod1.predict(x)

array([0. , 0. , 0. , 0.8, 0. , 0. , 0. , 0. , 0.2, 0.4, 0. , 0. , 0. ,
       0.6, 0.8, 0. , 0. , 0. , 0. , 1. , 1. , 1. , 0. , 0. , 0. , 0. ,
       0.6, 0. , 0. , 0.2, 0. , 0. , 0. , 0. , 0. , 0. , 0.4, 1. , 0.6,
       0.6, 0.2, 0.6, 0. , 0. , 0.2, 0. , 1. , 0.2, 1. , 1. , 1. , 1. ,
       1. , 0. , 0. , 1. , 0. , 0. , 1. , 1. , 1. , 1. , 0. , 1. , 0. ,
       0.4, 1. , 1. , 1. , 1. , 0. , 1. , 0. , 0.2, 1. , 0. , 1. , 0. ,
       0. , 1. , 1. , 1. , 0. , 0. , 1. , 0. , 0.8, 0. , 1. , 0.8, 0.8,
       0.8, 0.2, 1. , 0. , 0. , 1. , 1. , 1. , 0.6, 0. , 1. , 1. , 1. ,
       1. , 0.2, 1. , 1. , 0. , 1. , 1. , 1. , 0.8, 1. , 1. , 0.8, 1. ,
       0. , 0. , 0. , 1. , 0. , 0. , 1. , 1. , 1. , 0.4, 0. , 0.8, 0. ,
       1. , 0. , 0. , 0.6, 0. , 0.8, 1. , 1. , 0. , 1. , 1. , 0. , 1. ,
       0.8, 1. , 1. , 0.8, 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ,
       0. , 0.4, 1. , 1. , 1. , 0. , 0. , 1. , 0. , 1. , 1. , 0. , 0. ,
       1. , 1. , 0. , 0. , 1. , 1. , 1. , 1. , 0.4, 1. , 1. , 0.

In [ ]:
data3=datasets.load_iris()

In [ ]:
data3

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [ ]:
import numpy as np
import pandas as pd
data4=pd.DataFrame(data3.data,columns=data3.feature_names)
data4

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [ ]:
a = data4
b = data3.target



In [ ]:
a

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [ ]:
b

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
Model1 = LinearRegression()

In [ ]:
Model1.fit(a,b)

LinearRegression()

In [ ]:
Model1.predict(a)

array([-8.25493616e-02, -4.01284476e-02, -4.86276768e-02,  1.22998627e-02,
       -7.53667248e-02,  5.82910066e-02,  3.83367194e-02, -4.44863248e-02,
        1.98324281e-02, -8.21970989e-02, -1.01272512e-01,  7.59348686e-04,
       -8.98630676e-02, -1.02503649e-01, -2.26652208e-01, -4.10494982e-02,
       -3.31670043e-02, -2.16241562e-02, -3.21980063e-02, -1.07834994e-02,
       -4.35196609e-02,  5.41496547e-02, -1.22062394e-01,  1.76835660e-01,
        6.93528569e-02, -5.59002750e-03,  1.00228589e-01, -7.08754443e-02,
       -8.97319983e-02,  1.99658314e-02,  1.27831946e-02,  3.26017444e-02,
       -1.55848342e-01, -1.55367344e-01, -2.12718935e-02, -1.05063936e-01,
       -1.50176206e-01, -1.25101345e-01, -7.04002332e-03, -5.56769102e-02,
       -3.32980735e-02,  7.07502372e-02, -1.50559206e-02,  2.18071051e-01,
        1.41599717e-01,  3.19873432e-02, -4.88442021e-02, -1.45725887e-02,
       -9.00819270e-02, -6.33428789e-02,  1.20248442e+00,  1.28482413e+00,
        1.32433716e+00,  

In [ ]:
from sklearn.neighbors import KNeighborsRegressor

In [ ]:
Mod1 = KNeighborsRegressor()

In [ ]:
Mod1.fit(a,b)

KNeighborsRegressor()

In [ ]:
Mod1.predict(a)

array([0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 1. , 1. ,
       1. , 1. , 1. , 1. , 1.2, 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ,
       1. , 1. , 1. , 1.2, 1. , 1.6, 1. , 1.6, 1. , 1. , 1. , 1. , 1.4,
       1. , 1. , 1. , 1. , 1. , 1.8, 1. , 1. , 1. , 1. , 1. , 1. , 1. ,
       1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 2. , 2. , 2. , 2. ,
       2. , 2. , 1.2, 2. , 2. , 2. , 1.8, 2. , 2. , 2. , 2. , 2. , 2. ,
       2. , 2. , 1.4, 2. , 2. , 2. , 1.8, 2. , 2. , 2. , 1.8, 2. , 2. ,
       2. , 2. , 2. , 1.6, 1.8, 2. , 2. , 2. , 1.8, 2. , 2. , 2. , 2. ,
       2. , 2. , 2. , 1.8, 2. , 2. , 2. ])

In [ ]:
data5=datasets.load_wine()

In [ ]:
data5

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [ ]:
import numpy as np
import pandas as pd
data6=pd.DataFrame(data5.data,columns=data5.feature_names)
data6

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  
0                            3.92   1065.0  
1                            3.40   1050.0  
2                            3.17   1185.0  
3                            3.45   1480.0  
4                            2.93    735.0  
..                            ...      ...  
173                          1.74    740.0  
174                          1.56    750.0  
175                          1.56    835.0  
176                          1.62    840.0  
177                          1.60    560.0  

[178 rows x 13 columns]

In [ ]:
m = data6
n = data5.target


In [ ]:
m

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  
0                            3.92   1065.0  
1                            3.40   1050.0  
2                            3.17   1185.0  
3                            3.45   1480.0  
4                            2.93    735.0  
..                            ...      ...  
173                          1.74    740.0  
174                          1.56    750.0  
175                          1.56    835.0  
176                          1.62    840.0  
177                          1.60    560.0  

[178 rows x 13 columns]

In [ ]:
n

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
Model2 = LinearRegression()

In [ ]:
Model2.fit(m,n)

LinearRegression()

In [ ]:
Model2.predict(m)

array([-0.20583068, -0.09170449,  0.10590583, -0.14530482,  0.57562303,
       -0.19676999, -0.2002875 , -0.10788718, -0.01030284,  0.11177235,
       -0.23721839,  0.08419978,  0.02660894, -0.41397361, -0.43556848,
        0.12152653,  0.10055915,  0.20410908, -0.37899527,  0.1571841 ,
        0.09275278,  0.52126955, -0.20861091,  0.20306296,  0.15921052,
        0.43597758, -0.04447262,  0.28210749,  0.08333864,  0.16477324,
        0.20723779,  0.04713043,  0.14709764,  0.0734232 ,  0.23681769,
        0.28327839,  0.25594129,  0.40573179,  0.2413795 ,  0.10914819,
        0.25344433,  0.39427315, -0.22130187,  0.64129341,  0.34827332,
        0.26151107, -0.01944663,  0.1119608 ,  0.35614068,  0.06522601,
        0.16760752, -0.13697218, -0.13542614,  0.04074458,  0.17065318,
        0.48418909,  0.22479111,  0.03725965,  0.00446375,  1.37135018,
        1.16118588,  1.52958303,  0.86353501,  0.90534813,  1.10417003,
        0.76129249,  0.55651909,  0.92709211,  0.98496005,  0.95

In [ ]:
from sklearn.neighbors import KNeighborsRegressor

In [ ]:
Mod2 = KNeighborsRegressor()

In [ ]:
Mod2.fit(m,n)

KNeighborsRegressor()

In [ ]:
Mod2.predict(m)

array([0. , 0. , 0. , 0. , 1.4, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 1.2, 0.2, 1.4, 0. , 0. , 1.2, 1.2,
       0. , 0. , 0.2, 0. , 0. , 0. , 0. , 0. , 0. , 0.6, 0.8, 0. , 0. ,
       0.8, 0.4, 0. , 0. , 1.2, 0.8, 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0.2, 0. , 0. , 1.4, 1.2, 1. , 1.6, 1.2, 1. ,
       1. , 1. , 1.2, 1.4, 0.8, 0.8, 1.2, 1.4, 0.4, 0.8, 1. , 1. , 1.6,
       0.4, 1. , 1. , 1.6, 1.4, 1.4, 1.6, 1. , 1. , 1.4, 1.2, 1.6, 1.4,
       1. , 1. , 1. , 1. , 0.4, 1.6, 1. , 1.6, 1.2, 1.6, 1.4, 1. , 1.2,
       1. , 1. , 1.2, 1. , 1. , 0.8, 1.8, 1. , 1.8, 1. , 1. , 1.2, 1. ,
       1. , 1. , 1.4, 1.6, 1.2, 1. , 1. , 1. , 1. , 1. , 1.4, 1. , 1.2,
       1.6, 1.8, 1.4, 1.8, 1.8, 1.4, 1.6, 1.8, 1.4, 1.8, 1.8, 1.2, 1.8,
       1.6, 1. , 1.2, 1.2, 1.6, 1.8, 1.8, 1.8, 1.4, 1.2, 1.2, 1.6, 1.6,
       1.4, 0.8, 1.8, 1.6, 1.6, 1.2, 1.6, 1.2, 1.6, 1.6, 1.4, 1.4, 1.4,
       1.6, 1.6, 1.4, 1.8, 1.8, 1.4, 1.2, 1.2, 1.6])

Data preprocessing stage

*   Handling Missing Values
*   String to numeric values



# Handling Missing Values using simple imputer method

So the simple imputer method fills the null values present in the table with raw data by using multiple tendencies such as Mean , Median , Mode.

set_option is used to print the entire data

In [ ]:
from sklearn.impute import SimpleImputer
import pandas as pd
pd.set_option("display.max_rows",None)
crcdata=pd.read_csv('/content/CricketData.csv')
crcdata

Player       Span  Mat  Inns  NO   Runs    HS    Ave  \
0           DG Bradman (AUS)  1928-1948   52    80  10   6996   334  99.94   
1             HC Brook (ENG)  2022-2023   12    20   1   1181   186  62.15   
2             AC Voges (AUS)  2015-2016   20    31   7   1485  269*  61.87   
3            RG Pollock (SA)  1963-1970   23    41   4   2256   274  60.97   
4            GA Headley (WI)  1930-1954   22    40   4   2190  270*  60.83   
5          H Sutcliffe (ENG)  1924-1935   54    84   9   4555   194  60.73   
6            E Paynter (ENG)  1931-1939   20    31   5   1540   243  59.23   
7        KF Barrington (ENG)  1955-1968   82   131  15   6806   256  58.67   
8             ED Weekes (WI)  1948-1958   48    81   5   4455   207  58.61   
9           WR Hammond (ENG)  1927-1947   85   140  16   7249  336*  58.45   
10            GS Sobers (WI)  1954-1974   93   160  21   8032  365*  57.78   
11            GS Sobers (WI)  1954-1974   93   160  21   8032  365*  57.78   
12        KC Sangakkara (SL)  2000-2015  134   233  17  12400   319  57.40   
13           SPD Smith (AUS)  2010-2024  109   195  25   9685   239  56.97   
14            JB Hobbs (ENG)  1908-1930   61   102   7   5410   211  56.94   
15           CL Walcott (WI)  1948-1960   44    74   7   3798   220  56.68   
16            L Hutton (ENG)  1937-1955   79   138  15   6971   364  56.67   
17        JH Kallis (ICC/SA)  1995-2013  166   280  40  13289   224  55.37   
18        GE Tyldesley (ENG)  1921-1929   14    20   2    990   122  55.00   
19        KS Williamson (NZ)  2010-2024  100   176  17   8743   251  54.98   
20             CA Davis (WI)  1968-1973   15    29   5   1301   183  54.20   
21             CA Davis (WI)  1968-1973   15    29   5   1301   183  54.20   
22           VG Kambli (IND)  1993-1995   17    21   1   1084   227  54.20   
23         GS Chappell (AUS)  1970-1984   87   151  19   7110  247*  53.86   
24            AD Nourse (SA)  1935-1951   34    62   7   2960   231  53.81   
25        SR Tendulkar (IND)  1989-2013  200   329  33  15921  248*  53.78   
26          BC Lara (ICC/WI)  1990-2006  131   232   6  11953  400*  52.88   
27       Javed Miandad (PAK)  1976-1993  124   189  21   8832  280*  52.57   
28        R Dravid (ICC/IND)  1996-2012  164   286  32  13288   270  52.31   
29     Mohammad Yousuf (PAK)  1998-2010   90   156  12   7530   223  52.29   
30         Younis Khan (PAK)  2000-2017  118   213  19  10099   313  52.05   
31          RT Ponting (AUS)  1995-2012  168   287  29  13378   257  51.85   
32             J Ryder (AUS)  1920-1929   20    32   5   1394  201*  51.62   
33            A Flower (ZIM)  1992-2002   63   112  19   4794  232*  51.54   
34          MEK Hussey (AUS)  2005-2013   79   137  16   6235   195  51.52   
35        S Chanderpaul (WI)  1994-2015  164   280  49  11867  203*  51.37   
36         SM Gavaskar (IND)  1971-1987  125   214  16  10122  236*  51.12   
37            SR Waugh (AUS)  1985-2004  168   260  46  10927   200  51.06   
38           ML Hayden (AUS)  1994-2009  103   184  14   8625   380  50.73   
39       AB de Villiers (SA)  2004-2018  114   191  18   8765  278*  50.66   
40           AR Border (AUS)  1978-1994  156   265  44  11174   205  50.56   
41           AR Border (AUS)  1978-1994  156   265  44  11174   205  50.56   
42          DJ Mitchell (NZ)  2019-2024   23    37   5   1608   190  50.25   
43         IVA Richards (WI)  1974-1991  121   182  12   8540   291  50.23   
44         DCS Compton (ENG)  1937-1957   78   131  15   5807   278  50.06   
45     DPMD Jayawardene (SL)  1997-2014  149   252  15  11814   374  49.84   
46             JE Root (ENG)  2012-2024  140   257  21  11736   254  49.72   
47  Inzamam-ul-Haq (ICC/PAK)  1992-2007  120   200  22   8830   329  49.60   
48       M Labuschagne (AUS)  2018-2024   50    90   7   4114   215  49.56   
49          FMM Worrell (WI)  1948-1963   51    87   9   3860   261  49.48   
50             CP Mead (ENG)  1911-1928   17

In [ ]:
crcdata.isna()

Player   Span    Mat   Inns     NO   Runs     HS    Ave     BF     SR  \
0    False  False  False  False  False  False  False  False  False  False   
1    False  False  False  False  False  False  False  False  False  False   
2    False  False  False  False  False  False  False  False  False  False   
3    False  False  False  False  False  False  False  False  False  False   
4    False  False  False  False  False  False  False  False  False  False   
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
62   False  False  False  False  False  False  False  False  False  False   
63   False  False  False  False  False  False  False  False  False  False   
64   False  False  False  False  False  False  False  False   True  False   
65   False  False  False  False  False  False  False  False  False  False   
66   False  False  False  False  False  False  False  False  False   True   

      100     50      0     4s     6s  
0   False  False  False  False  False  
1   False  False  False  False  False  
2   False  False  False  False  False  
3   False  False  False  False  False  
4   False  False  False  False  False  
..    ...    ...    ...    ...    ...  
62  False  False  False  False  False  
63  False  False  False  False  False  
64  False  False  False  False  False  
65  False  False  False  False  False  
66  False  False  False  False  False  

[67 rows x 15 columns]

In [ ]:
crcdata.isna().sum()

Player    0
Span      0
Mat       0
Inns      0
NO        0
Runs      0
HS        0
Ave       0
BF        4
SR        4
100       0
50        0
0         0
4s        0
6s        0
dtype: int64

In [ ]:
from sklearn.impute import SimpleImputer

drop the string values

In [ ]:
crcdata.drop(columns =["Player","Span",], inplace = True )


In [ ]:
crcdata.drop(columns =["SR","Ave"], inplace = True )

# Mean strategy = 'Mean'

In [ ]:
impute_mean = SimpleImputer(strategy = "mean")
impute_mean.fit_transform(crcdata)

array([[5.20000000e+01, 8.00000000e+01, 1.00000000e+01, 6.99600000e+03,
        9.99400000e+01, 5.86000000e+01, 2.90000000e+01, 1.30000000e+01,
        7.00000000e+00],
       [1.20000000e+01, 2.00000000e+01, 1.00000000e+00, 1.18100000e+03,
        6.21500000e+01, 9.17600000e+01, 4.00000000e+00, 7.00000000e+00,
        1.00000000e+00],
       [2.00000000e+01, 3.10000000e+01, 7.00000000e+00, 1.48500000e+03,
        6.18700000e+01, 5.56800000e+01, 5.00000000e+00, 4.00000000e+00,
        2.00000000e+00],
       [2.30000000e+01, 4.10000000e+01, 4.00000000e+00, 2.25600000e+03,
        6.09700000e+01, 5.44800000e+01, 7.00000000e+00, 1.10000000e+01,
        1.00000000e+00],
       [2.20000000e+01, 4.00000000e+01, 4.00000000e+00, 2.19000000e+03,
        6.08300000e+01, 5.60000000e+01, 1.00000000e+01, 5.00000000e+00,
        2.00000000e+00],
       [5.40000000e+01, 8.40000000e+01, 9.00000000e+00, 4.55500000e+03,
        6.07300000e+01, 3.45900000e+01, 1.60000000e+01, 2.30000000e+01,
        2.0

Convert rawdata into readlable data

In [ ]:
crcdata=pd.DataFrame(crcdata,columns=['Mat','Inns','NO','Runs','Ave','100','50','0'])
crcdata

Mat  Inns  NO   Runs    Ave  100  50   0
0    52    80  10   6996  99.94   29  13   7
1    12    20   1   1181  62.15    4   7   1
2    20    31   7   1485  61.87    5   4   2
3    23    41   4   2256  60.97    7  11   1
4    22    40   4   2190  60.83   10   5   2
5    54    84   9   4555  60.73   16  23   2
6    20    31   5   1540  59.23    4   7   3
7    82   131  15   6806  58.67   20  35   5
8    48    81   5   4455  58.61   15  19   6
9    85   140  16   7249  58.45   22  24   4
10   93   160  21   8032  57.78   26  30  12
11   93   160  21   8032  57.78   26  30  12
12  134   233  17  12400  57.40   38  52  11
13  109   195  25   9685  56.97   32  41  10
14   61   102   7   5410  56.94   15  28   4
15   44    74   7   3798  56.68   15  14   1
16   79   138  15   6971  56.67   19  33   5
17  166   280  40  13289  55.37   45  58  16
18   14    20   2    990  55.00    3   6   2
19  100   176  17   8743  54.98   32  34  11
20   15    29   5   1301  54.20    4   4   1
21   15    29   5   1301  54.20    4   4   1
22   17    21   1   1084  54.20    4   3   3
23   87   151  19   7110  53.86   24  31  12
24   34    62   7   2960  53.81    9  14   3
25  200   329  33  15921  53.78   51  68  14
26  131   232   6  11953  52.88   34  48  17
27  124   189  21   8832  52.57   23  43   6
28  164   286  32  13288  52.31   36  63   8
29   90   156  12   7530  52.29   24  33  11
30  118   213  19  10099  52.05   34  33  19
31  168   287  29  13378  51.85   41  62  17
32   20    32   5   1394  51.62    3   9   1
33   63   112  19   4794  51.54   12  27   5
34   79   137  16   6235  51.52   19  29  12
35  164   280  49  11867  51.37   30  66  15
36  125   214  16  10122  51.12   34  45  12
37  168   260  46  10927  51.06   32  50  22
38  103   184  14   8625  50.73   30  29  14
39  114   191  18   8765  50.66   22  46   8
40  156   265  44  11174  50.56   27  63  11
41  156   265  44  11174  50.56   27  63  11
42   23    37   5   1608  50.25    5  10   1
43  121   182  12   8540  50.23   24  45  10
44   78   131  15   5807  50.06   17  28  10
45  149   252  15  11814  49.84   34  50  15
46  140   257  21  11736  49.72   31  61  12
47  120   200  22   8830  49.60   25  46  15
48   50    90   7   4114  49.56   11  20   4
49   51    87   9   3860  49.48    9  22  11
50   17    26   2   1185  49.37    4   3   3
51  104   180   6   8586  49.34   23  32  16
52  104   180   6   8586  49.34   23  32  16
53   16    26   2   1180  49.16    4   3   2
54  113   191  11   8848  49.15   29  30  14
55  115   198  22   8643  49.10   28  27   9
56   21    39   5   1669  49.08    3   9   2
57   42    80   9   3471  48.88    8  21   3
58   20    33   4   1415  48.79    5   6   3
59   81   132  20   5462  48.76   14  30  11
60   79   137  10   6149  48.41   21  24   7
61   74   125  14   5357  48.26   15  33   4
62  117   205  13   9265  48.25   27  38  11
63   29    48   4   2122  48.22    7   6   1
64   39    62   5   2748  48.21    6  13   4
65   39    62   5   2748  48.21    6  13   4
66   22    33   6   1296  48.00    1  10   2

In [ ]:
Numerical_CricketData.to_csv('Numerical_Cricket_data.csv',index=False)

NameError: name 'Numerical_CricketData' is not defined

In [ ]:
#impute_median = SimpleImputer(strategy = 'median')
#impute_median.fit_tranform(crcdata)

#impute_mode = SimpleImputer(strategy = 'most_Frequent')
#impute_mode.fit_tranform(crcdata)

#impute_constant = SimpleImputer(strategy = 'constant',fill_values=14)
#impute_constant.fit_tranform(crcdata)



# Median strategy = 'Median'

In [ ]:
impute_median = SimpleImputer(strategy = "median")
impute_median.fit_transform(crcdata)

array([[5.2000e+01, 8.0000e+01, 1.0000e+01, 6.9960e+03, 2.9000e+01,
        1.3000e+01, 7.0000e+00],
       [1.2000e+01, 2.0000e+01, 1.0000e+00, 1.1810e+03, 4.0000e+00,
        7.0000e+00, 1.0000e+00],
       [2.0000e+01, 3.1000e+01, 7.0000e+00, 1.4850e+03, 5.0000e+00,
        4.0000e+00, 2.0000e+00],
       [2.3000e+01, 4.1000e+01, 4.0000e+00, 2.2560e+03, 7.0000e+00,
        1.1000e+01, 1.0000e+00],
       [2.2000e+01, 4.0000e+01, 4.0000e+00, 2.1900e+03, 1.0000e+01,
        5.0000e+00, 2.0000e+00],
       [5.4000e+01, 8.4000e+01, 9.0000e+00, 4.5550e+03, 1.6000e+01,
        2.3000e+01, 2.0000e+00],
       [2.0000e+01, 3.1000e+01, 5.0000e+00, 1.5400e+03, 4.0000e+00,
        7.0000e+00, 3.0000e+00],
       [8.2000e+01, 1.3100e+02, 1.5000e+01, 6.8060e+03, 2.0000e+01,
        3.5000e+01, 5.0000e+00],
       [4.8000e+01, 8.1000e+01, 5.0000e+00, 4.4550e+03, 1.5000e+01,
        1.9000e+01, 6.0000e+00],
       [8.5000e+01, 1.4000e+02, 1.6000e+01, 7.2490e+03, 2.2000e+01,
        2.4000e+01, 4.0

# Mode strategy = 'Most_frequent'

In [ ]:
impute_mode = SimpleImputer(strategy = "most_frequent")
impute_mode.fit_transform(crcdata)

array([[   52,    80,    10,  6996,    29,    13,     7],
       [   12,    20,     1,  1181,     4,     7,     1],
       [   20,    31,     7,  1485,     5,     4,     2],
       [   23,    41,     4,  2256,     7,    11,     1],
       [   22,    40,     4,  2190,    10,     5,     2],
       [   54,    84,     9,  4555,    16,    23,     2],
       [   20,    31,     5,  1540,     4,     7,     3],
       [   82,   131,    15,  6806,    20,    35,     5],
       [   48,    81,     5,  4455,    15,    19,     6],
       [   85,   140,    16,  7249,    22,    24,     4],
       [   93,   160,    21,  8032,    26,    30,    12],
       [   93,   160,    21,  8032,    26,    30,    12],
       [  134,   233,    17, 12400,    38,    52,    11],
       [  109,   195,    25,  9685,    32,    41,    10],
       [   61,   102,     7,  5410,    15,    28,     4],
       [   44,    74,     7,  3798,    15,    14,     1],
       [   79,   138,    15,  6971,    19,    33,     5],
       [  166,

In [ ]:
hello = pd.DataFrame({'first_hits':[10,20,30,np.NaN,40,50,60,40,30]})
hello

first_hits
0        10.0
1        20.0
2        30.0
3         NaN
4        40.0
5        50.0
6        60.0
7        40.0
8        30.0

In [ ]:
impute_1 = SimpleImputer(strategy='mean')
impute_1.fit_transform(hello)

array([[10.],
       [20.],
       [30.],
       [35.],
       [40.],
       [50.],
       [60.],
       [40.],
       [30.]])

In [ ]:
impute_2 = SimpleImputer(strategy='median')
impute_2.fit_transform(hello)

array([[10.],
       [20.],
       [30.],
       [35.],
       [40.],
       [50.],
       [60.],
       [40.],
       [30.]])

In [ ]:
impute_3 = SimpleImputer(strategy='most_frequent')
impute_3.fit_transform(hello)

array([[10.],
       [20.],
       [30.],
       [30.],
       [40.],
       [50.],
       [60.],
       [40.],
       [30.]])

In [ ]:
h1 = pd.DataFrame({'first_hit':[10,np.NaN,np.NaN,40,np.NaN]})
h1

first_hit
0       10.0
1        NaN
2        NaN
3       40.0
4        NaN

In [ ]:
impute_4 = SimpleImputer(strategy='mean')
impute_4.fit_transform(h1)

array([[10.],
       [25.],
       [25.],
       [40.],
       [25.]])

In [ ]:
impute_5 = SimpleImputer(strategy='median')
impute_5.fit_transform(h1)

array([[10.],
       [25.],
       [25.],
       [40.],
       [25.]])

In [ ]:
impute_6 = SimpleImputer(strategy='most_frequent')
impute_6.fit_transform(h1)

array([[10.],
       [10.],
       [10.],
       [40.],
       [10.]])

# Train Test Split

Train Test Split is a fundamental technique of data preprocessing where it involves splitting the datasets into model training data and model testing data.

In [ ]:
from sklearn import datasets
data1=datasets.load_breast_cancer()
data1


{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [ ]:
import numpy as np
import pandas as pd
data2=pd.DataFrame(data1.data,columns=data1.feature_names)
data2

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0         17.990         10.38          122.80     1001.0          0.11840   
1         20.570         17.77          132.90     1326.0          0.08474   
2         19.690         21.25          130.00     1203.0          0.10960   
3         11.420         20.38           77.58      386.1          0.14250   
4         20.290         14.34          135.10     1297.0          0.10030   
5         12.450         15.70           82.57      477.1          0.12780   
6         18.250         19.98          119.60     1040.0          0.09463   
7         13.710         20.83           90.20      577.9          0.11890   
8         13.000         21.82           87.50      519.8          0.12730   
9         12.460         24.04           83.97      475.9          0.11860   
10        16.020         23.24          102.70      797.8          0.08206   
11        15.780         17.89          103.60      781.0          0.09710   
12        19.170         24.80          132.40     1123.0          0.09740   
13        15.850         23.95          103.70      782.7          0.08401   
14        13.730         22.61           93.60      578.3          0.11310   
15        14.540         27.54           96.73      658.8          0.11390   
16        14.680         20.13           94.74      684.5          0.09867   
17        16.130         20.68          108.10      798.8          0.11700   
18        19.810         22.15          130.00     1260.0          0.09831   
19        13.540         14.36           87.46      566.3          0.09779   
20        13.080         15.71           85.63      520.0          0.10750   
21         9.504         12.44           60.34      273.9          0.10240   
22        15.340         14.26          102.50      704.4          0.10730   
23        21.160         23.04          137.20     1404.0          0.09428   
24        16.650         21.38          110.00      904.6          0.11210   
25        17.140         16.40          116.00      912.7          0.11860   
26        14.580         21.53           97.41      644.8          0.10540   
27        18.610         20.25          122.10     1094.0          0.09440   
28        15.300         25.27          102.40      732.4          0.10820   
29        17.570         15.05          115.00      955.1          0.09847   
30        18.630         25.11          124.80     1088.0          0.10640   
31        11.840         18.70           77.93      440.6          0.11090   
32        17.020         23.98          112.80      899.3          0.11970   
33        19.270         26.47          127.90     1162.0          0.09401   
34        16.130         17.88          107.00      807.2          0.10400   
35        16.740         21.59          110.10      869.5          0.09610   
36        14.250         21.72           93.63      633.0          0.09823   
37        13.030         18.42           82.61      523.8          0.08983   
38        14.990         25.20           95.54      698.8          0.09387   
39        13.480         20.82           88.40      559.2          0.10160   
40        13.440         21.58           86.18      563.0          0.08162   
41        10.950         21.35           71.90      371.1          0.12270   
42        19.070         24.81          128.30     1104.0          0.09081   
43        13.280         20.28           87.32      545.2          0.10410   
44        13.170         21.81           85.42      531.5          0.09714   
45        18.650         17.60          123.70     1076.0          0.10990   
46         8.196         16.84           51.71      201.9          0.08600   
47        13.170         18.66           85.98      534.6          0.11580   
48        12.050         14.63           78.04      449.3          0.10310   
49        13.490         22.30           86.91      561.0          0.08752   
50        11.760         21

In [ ]:
x = data2
y = data1.target


In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [ ]:
print(x.shape,x_train.shape,x_test.shape)

(569, 30) (455, 30) (114, 30)


In [ ]:
print(y.shape,y_train.shape,y_test.shape)

(569,) (455,) (114,)


In [ ]:
x_train.describe()

mean radius  mean texture  mean perimeter    mean area  \
count   455.000000    455.000000      455.000000   455.000000   
mean     14.094982     19.323626       91.741165   651.874066   
std       3.515644      4.177824       24.084248   348.824016   
min       6.981000      9.710000       43.790000   143.500000   
25%      11.665000     16.370000       74.860000   416.700000   
50%      13.210000     18.910000       85.980000   538.700000   
75%      15.780000     21.815000      103.900000   782.650000   
max      28.110000     33.810000      188.500000  2499.000000   

       mean smoothness  mean compactness  mean concavity  mean concave points  \
count       455.000000        455.000000      455.000000           455.000000   
mean          0.096627          0.104700        0.089630             0.048982   
std           0.014020          0.050960        0.077837             0.037664   
min           0.062510          0.019380        0.000000             0.000000   
25%           0.086760          0.066525        0.030155             0.020750   
50%           0.096100          0.095880        0.065920             0.034380   
75%           0.105400          0.130500        0.132200             0.074095   
max           0.163400          0.311400        0.426800             0.201200   

       mean symmetry  mean fractal dimension  ...  worst radius  \
count     455.000000              455.000000  ...    455.000000   
mean        0.181383                0.062938  ...     16.232655   
std         0.027316                0.007306  ...      4.778027   
min         0.106000                0.049960  ...      7.930000   
25%         0.161900                0.057805  ...     12.975000   
50%         0.179400                0.061610  ...     14.980000   
75%         0.196050                0.066180  ...     19.025000   
max         0.274300                0.097440  ...     33.130000   

       worst texture  worst perimeter   worst area  worst smoothness  \
count     455.000000       455.000000   455.000000        455.000000   
mean       25.735890       106.951407   875.582857          0.132714   
std         6.075564        32.963913   556.711871          0.023362   
min        12.020000        50.410000   185.200000          0.071170   
25%        21.360000        83.920000   513.550000          0.117050   
50%        25.460000        97.820000   687.600000          0.131600   
75%        29.585000       126.300000  1091.500000          0.146900   
max        47.160000       229.300000  3432.000000          0.222600   

       worst compactness  worst concavity  worst concave points  \
count         455.000000       455.000000            455.000000   
mean            0.254444         0.274887              0.114798   
std             0.155840         0.208912              0.064627   
min             0.027290         0.000000              0.000000   
25%             0.148600         0.116600              0.064530   
50%             0.216400         0.229800              0.101700   
75%             0.333800         0.388400              0.161350   
max             1.058000         1.252000              0.275600   

       worst symmetry  worst fractal dimension  
count      455.000000               455.000000  
mean         0.292186                 0.084263  
std          0.062530                 0.018653  
min          0.156500                 0.055040  
25%          0.252600                 0.071880  
50%          0.284200                 0.080200  
75%          0.319700                 0.092100  
max          0.663800                 0.207500  

[8 rows x 30 columns]

In [ ]:
y_train.describe()

AttributeError: 'numpy.ndarray' object has no attribute 'describe'

In [ ]:
x_train

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
413       14.990         22.11           97.53      693.7          0.08515   
127       19.000         18.91          123.40     1138.0          0.08217   
1         20.570         17.77          132.90     1326.0          0.08474   
522       11.260         19.83           71.30      388.1          0.08511   
359        9.436         18.32           59.82      278.6          0.10090   
380       11.270         12.96           73.16      386.3          0.12370   
207       17.010         20.26          109.70      904.3          0.08772   
111       12.630         20.76           82.15      480.4          0.09933   
338       10.050         17.53           64.41      310.8          0.10070   
169       14.970         16.95           96.22      685.9          0.09855   
251       11.500         18.45           73.28      407.4          0.09345   
399       11.800         17.26           75.26      431.9          0.09087   
546       10.320         16.35           65.31      324.9          0.09434   
299       10.510         23.09           66.85      334.2          0.10150   
28        15.300         25.27          102.40      732.4          0.10820   
419       11.160         21.41           70.95      380.3          0.10180   
200       12.230         19.56           78.54      461.0          0.09586   
12        19.170         24.80          132.40     1123.0          0.09740   
21         9.504         12.44           60.34      273.9          0.10240   
336       12.990         14.23           84.08      514.3          0.09462   
553        9.333         21.94           59.01      264.0          0.09240   
368       21.710         17.25          140.90     1546.0          0.09384   
477       13.900         16.62           88.97      599.4          0.06828   
487       19.440         18.82          128.10     1167.0          0.10890   
262       17.290         22.13          114.40      947.8          0.08999   
288       11.260         19.96           73.72      394.1          0.08020   
308       13.500         12.71           85.69      566.2          0.07376   
321       20.160         19.66          131.10     1274.0          0.08020   
471       12.040         28.14           76.85      449.9          0.08752   
306       13.200         15.82           84.07      537.3          0.08511   
385       14.600         23.29           93.97      664.7          0.08682   
186       18.310         18.58          118.60     1041.0          0.08588   
555       10.290         27.61           65.67      321.4          0.09030   
31        11.840         18.70           77.93      440.6          0.11090   
343       19.680         21.68          129.90     1194.0          0.09797   
174       10.660         15.15           67.49      349.6          0.08792   
381       11.040         14.93           70.67      372.7          0.07987   
489       16.690         20.20          107.10      857.6          0.07497   
418       12.700         12.17           80.88      495.0          0.08785   
524        9.847         15.68           63.00      293.2          0.09492   
91        15.370         22.76          100.20      728.2          0.09200   
52        11.940         18.24           75.71      437.6          0.08261   
15        14.540         27.54           96.73      658.8          0.11390   
167       16.780         18.80          109.30      886.3          0.08865   
517       19.890         20.26          130.50     1214.0          0.10370   
437       14.040         15.98           89.78      611.2          0.08458   
231       11.320         27.08           71.76      395.7          0.06883   
236       23.210         26.97          153.50     1670.0          0.09509   
143       12.900         15.92           83.74      512.2          0.08677   
49        13.490         22.30           86.91      561.0          0.08752   
75        16.070         19

In [ ]:
from sklearn.linear_model import LinearRegression
Model3=LinearRegression()

In [ ]:
Model3.fit(x,y)

LinearRegression()

In [ ]:
Model3.predict(x_train)

array([ 5.52500714e-01,  3.43417460e-01,  1.57869645e-01,  1.13416498e+00,
        8.93551398e-01,  7.52853516e-01,  4.04762039e-01,  7.15977232e-01,
        1.04544116e+00,  8.78804118e-01,  9.14000702e-01,  9.19826813e-01,
        1.15115923e+00,  1.09391552e+00,  4.69024100e-03,  9.60108149e-01,
        6.43836899e-01,  3.58799952e-01,  1.12677621e+00,  1.11323878e+00,
        1.13288870e+00,  3.13569039e-01,  9.49092523e-01, -1.47262148e-01,
        3.11047236e-01,  7.95388756e-01,  1.10743721e+00,  2.95913645e-01,
        7.41410930e-01,  1.03802798e+00,  4.43675811e-01,  4.01501123e-01,
        8.76269939e-01,  8.49150658e-02, -1.35394975e-01,  1.18645327e+00,
        1.07946948e+00,  4.84641907e-01,  8.80380171e-01,  1.04414557e+00,
        4.97307026e-01,  9.27637316e-01,  6.59600231e-03,  3.22067716e-01,
        1.06940678e-01,  7.19231344e-01,  1.05703930e+00, -1.72462373e-01,
        8.21827523e-01,  6.88486808e-01,  1.85995074e-01,  5.60575781e-02,
        3.12094215e-01, -

In [67]:
from sklearn.neighbors import KNeighborsRegressor
Model4=KNeighborsRegressor()

In [68]:
Model4.fit(x,y)

KNeighborsRegressor()

In [69]:
Model4.predict(x_test)

array([0.4, 1. , 0. , 1. , 0.6, 0.8, 1. , 0.4, 0. , 1. , 0.2, 0.4, 0. ,
       1. , 1. , 1. , 0. , 0. , 1. , 1. , 0. , 1. , 1. , 0. , 0. , 0. ,
       0. , 0. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 0. , 1. , 0. ,
       0.6, 1. , 1. , 1. , 0. , 1. , 1. , 1. , 0. , 1. , 1. , 1. , 1. ,
       1. , 0. , 1. , 1. , 0.6, 1. , 0.6, 1. , 1. , 0.6, 1. , 0.2, 0. ,
       1. , 0. , 1. , 0. , 1. , 0. , 1. , 1. , 0.6, 1. , 0.8, 1. , 0. ,
       0. , 0.6, 0. , 0. , 0. , 1. , 0.8, 1. , 0.8, 1. , 1. , 1. , 1. ,
       1. , 1. , 0. , 0.6, 0. , 1. , 0. , 1. , 1. , 1. , 0. , 1. , 0.8,
       1. , 0. , 1. , 0.8, 1. , 0. , 1. , 1. , 1. , 1. ])

In [70]:
Model5=LinearRegression()
Model5.fit(x_train,y_train)

LinearRegression()

In [71]:
Model5.predict(x_test)

array([ 0.62628821,  0.88634184,  0.15744438,  1.11550407,  0.77491911,
        0.27554389,  0.88812332,  0.7045598 ,  0.24073647,  1.15409007,
        0.1928371 ,  0.41231278,  0.54099604,  1.12848793,  0.82168487,
        0.80522252,  0.01715464, -0.13714104,  0.91979457,  0.89698332,
        0.18178006,  0.73306113,  0.99380784,  0.15632898, -0.30844574,
       -0.06642853, -0.3085799 ,  0.02793695,  1.15425097,  0.64820801,
        0.94154343,  0.61777863,  0.71878157,  1.00618666,  1.08696373,
        1.03120797,  0.22763312,  1.0289437 ,  0.23559896,  0.77930966,
        0.89375261,  1.13455039,  1.15444609,  0.10533538,  1.03587685,
        1.07177805,  0.94051118,  0.23493629,  1.23057474,  0.83711321,
        0.89365068,  0.6942735 ,  0.82635894, -0.12662031,  0.86259874,
        1.00400997,  0.6061643 ,  0.96538119,  0.7185692 ,  0.88339669,
        0.84726992,  0.5537479 ,  1.09542322,  0.6627464 ,  0.27075518,
        0.79746481,  0.0772083 ,  1.05673459, -0.25564652,  0.99